version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javimosch/chat-openapi-node
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - CHROMA_BASE_URL=http://chroma:8000
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    depends_on:
      - ollama
      - chroma

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      #- ./ollama:/root/.ollama
      - /home/jarancibia/.ollama:/root/.ollama
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma-db
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8123:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped

