version: '3'
services:
  traefik:
    image: traefik:latest
    ports:
      - "8085:8085"
      - "8084:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:8085"
      - "--providers.file.filename=/etc/traefik/dynamic/dynamic.yml"
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
    restart: unless-stopped
    environment:
      - APP_BACKEND_URL=http://192.168.1.103:3000