version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-openapi-node
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - chroma
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma-db
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8123:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3000","http://localhost:3001","http://localhost:3002","http://app:3000"]
    restart: unless-stopped

  # Streamlit-based ChromaDB UI
  chroma-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: chroma-ui
    ports:
      - "3001:8501"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma
    restart: unless-stopped

