version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: chat-openapi-node-dev
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
