version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-openapi-node
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
